services:
  app: 
    image: my-backend:latest
    container_name: bank-container

    environment:
      RDS_HOSTNAME: postgres-container
      RDS_PORT: 5432
      RDS_DB_NAME: mydatabase
      RDS_USERNAME: postgres
      RDS_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network
  
  frontend: 
    image: my-frontend:latest  
    container_name: frontend-container
    ports:
      - "3000:80" 
    networks:
      - app-network

networks:
  app-network:
    external: true



