
version: "3.8"


services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: ./backend
    image: my-backend:latest
    container_name: bank-container
    environment:
      RDS_HOSTNAME: postgres-container
      RDS_PORT: 5432
      RDS_DB_NAME: mydatabase
      RDS_USERNAME: postgres
      RDS_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: my-frontend:latest
    container_name: frontend-container
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:


#networks:
#  app-network:
#    driver: bridge





